trigger:
 none

pool: self-hosted
  #vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: 'latest'
        
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure Resouce Manager - MI'
        backendAzureRmStorageAccountName: 'terraformremotestate42'
        backendAzureRmContainerName: 'terraformstate-lessons'
        backendAzureRmKey: 'zero/terraform.tfstate'
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=tfplan'
        environmentServiceNameAzureRM: 'Azure Resouce Manager - MI'


- stage: Deploy
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: 'latest'
        
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure Resouce Manager - MI'
        backendAzureRmStorageAccountName: 'terraformremotestate42'
        backendAzureRmContainerName: 'terraformstate-lessons'
        backendAzureRmKey: 'zero/terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Azure Resouce Manager - MI'